# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: GSA - IT Modernization Centers of Excellence
email:  connectcoe@gsa.gov
description: >- # this means to ignore newlines until "baseurl:"
  The Centers of Excellence (CoE) are accelerating the modernization of IT 
  infrastructure across government by leveraging private sector innovation and 
  existing government services, and by centralizing best practices and expertise.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://coe.gsa.gov" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  # If all gem plugins have the same priority, they will be executed in the order
  # they are required, generally. Thus, if you have other plugins which generate
  # content and store that content in site.pages, site.posts, or site.collections,
  # be sure to require jekyll-sitemap either after those other gems if you want
  # the sitemap to include the generated content, or before those other gems if
  # you don't want the sitemap to include the generated content from the gems. 
  #                                 see: https://github.com/jekyll/jekyll-sitemap
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
collections:
  category:
    output: true
  ai_guide_for_government:
    output: true
    permalink: /coe/ai-guide-for-government/:slug/index.html

defaults:
  -
    scope:
      path: ""
      type: "ai_guide_for_government"
    values:
      layout: "ai-gfg"
